name: B&B w/ complex_proto

on:
  push:
  pull_request:

env:
  GRPC_REQUEST_SCENARIO: complex_proto

jobs:
  meta-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./generate_ci.sh | tee .github/workflows/build.yml
    - run: git --no-pager diff --exit-code

  set-image-name:
    runs-on: ubuntu-latest
    needs: [meta-check]
    outputs:
      name: ${{ steps.namer.outputs.name }}
    steps:
    - name: Set lowercase image name
      id: namer
      run: echo "::set-output name=name::ghcr.io/${SLUG,,}"
      env:
        SLUG: ${{ github.repository }}

  changed:
    runs-on: ubuntu-latest
    needs: [meta-check]
    outputs:
      files: ${{ steps.finder.outputs.all_changed_and_modified_files }}
      base: ${{ steps.base.outputs.base }}
    steps:
    - name: Deep checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      id: finder
      uses: tj-actions/changed-files@v26.1

    - name: Output whether base changed
      id: base
      run: echo "::set-output name=base::$BASE"
      env:
        BASE: >-
          ${{
          contains(steps.finder.outputs.all_changed_and_modified_files, '.dockerignore')     ||
          contains(steps.finder.outputs.all_changed_and_modified_files, 'analyze.sh')        ||
          contains(steps.finder.outputs.all_changed_and_modified_files, 'bench.sh')          ||
          contains(steps.finder.outputs.all_changed_and_modified_files, 'build.sh')          ||
          contains(steps.finder.outputs.all_changed_and_modified_files, 'clean.sh')          ||
          contains(steps.finder.outputs.all_changed_and_modified_files, 'collect_stats.sh')  ||
          contains(steps.finder.outputs.all_changed_and_modified_files, 'generate_ci.sh')    ||
          contains(steps.finder.outputs.all_changed_and_modified_files, 'proto/')            ||
          contains(steps.finder.outputs.all_changed_and_modified_files, 'setup_scenario.sh') }}


  cpp_brpc_bench:
    runs-on: ubuntu-latest
    needs:
    - set-image-name
    - changed
    if: fromJSON(needs.changed.outputs.base) || contains(needs.changed.outputs.files, 'cpp_brpc_bench/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build cpp_brpc_bench
      run: ./build.sh cpp_brpc_bench
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - name: Benchmark cpp_brpc_bench
      run: ./bench.sh cpp_brpc_bench
      env:
        GRPC_BENCHMARK_DURATION: 30s
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - if: github.ref == 'refs/heads/master'
      name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - if: github.ref == 'refs/heads/master'
      name: If on master push image to GHCR
      run: docker push $GRPC_IMAGE_NAME:cpp_brpc_bench-complex_proto
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}


  cpp_grpc_mt_bench:
    runs-on: ubuntu-latest
    needs:
    - set-image-name
    - changed
    if: fromJSON(needs.changed.outputs.base) || contains(needs.changed.outputs.files, 'cpp_grpc_mt_bench/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build cpp_grpc_mt_bench
      run: ./build.sh cpp_grpc_mt_bench
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - name: Benchmark cpp_grpc_mt_bench
      run: ./bench.sh cpp_grpc_mt_bench
      env:
        GRPC_BENCHMARK_DURATION: 30s
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - if: github.ref == 'refs/heads/master'
      name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - if: github.ref == 'refs/heads/master'
      name: If on master push image to GHCR
      run: docker push $GRPC_IMAGE_NAME:cpp_grpc_mt_bench-complex_proto
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}


  cpp_grpc_st_bench:
    runs-on: ubuntu-latest
    needs:
    - set-image-name
    - changed
    if: fromJSON(needs.changed.outputs.base) || contains(needs.changed.outputs.files, 'cpp_grpc_st_bench/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build cpp_grpc_st_bench
      run: ./build.sh cpp_grpc_st_bench
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - name: Benchmark cpp_grpc_st_bench
      run: ./bench.sh cpp_grpc_st_bench
      env:
        GRPC_BENCHMARK_DURATION: 30s
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - if: github.ref == 'refs/heads/master'
      name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - if: github.ref == 'refs/heads/master'
      name: If on master push image to GHCR
      run: docker push $GRPC_IMAGE_NAME:cpp_grpc_st_bench-complex_proto
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}


  go_connect_bench:
    runs-on: ubuntu-latest
    needs:
    - set-image-name
    - changed
    if: fromJSON(needs.changed.outputs.base) || contains(needs.changed.outputs.files, 'go_connect_bench/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build go_connect_bench
      run: ./build.sh go_connect_bench
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - name: Benchmark go_connect_bench
      run: ./bench.sh go_connect_bench
      env:
        GRPC_BENCHMARK_DURATION: 30s
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - if: github.ref == 'refs/heads/master'
      name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - if: github.ref == 'refs/heads/master'
      name: If on master push image to GHCR
      run: docker push $GRPC_IMAGE_NAME:go_connect_bench-complex_proto
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}


  go_grpc_bench:
    runs-on: ubuntu-latest
    needs:
    - set-image-name
    - changed
    if: fromJSON(needs.changed.outputs.base) || contains(needs.changed.outputs.files, 'go_grpc_bench/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build go_grpc_bench
      run: ./build.sh go_grpc_bench
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - name: Benchmark go_grpc_bench
      run: ./bench.sh go_grpc_bench
      env:
        GRPC_BENCHMARK_DURATION: 30s
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - if: github.ref == 'refs/heads/master'
      name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - if: github.ref == 'refs/heads/master'
      name: If on master push image to GHCR
      run: docker push $GRPC_IMAGE_NAME:go_grpc_bench-complex_proto
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}


  go_vtgrpc_bench:
    runs-on: ubuntu-latest
    needs:
    - set-image-name
    - changed
    if: fromJSON(needs.changed.outputs.base) || contains(needs.changed.outputs.files, 'go_vtgrpc_bench/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build go_vtgrpc_bench
      run: ./build.sh go_vtgrpc_bench
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - name: Benchmark go_vtgrpc_bench
      run: ./bench.sh go_vtgrpc_bench
      env:
        GRPC_BENCHMARK_DURATION: 30s
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - if: github.ref == 'refs/heads/master'
      name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - if: github.ref == 'refs/heads/master'
      name: If on master push image to GHCR
      run: docker push $GRPC_IMAGE_NAME:go_vtgrpc_bench-complex_proto
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}


  python_async_grpc_bench:
    runs-on: ubuntu-latest
    needs:
    - set-image-name
    - changed
    if: fromJSON(needs.changed.outputs.base) || contains(needs.changed.outputs.files, 'python_async_grpc_bench/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build python_async_grpc_bench
      run: ./build.sh python_async_grpc_bench
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - name: Benchmark python_async_grpc_bench
      run: ./bench.sh python_async_grpc_bench
      env:
        GRPC_BENCHMARK_DURATION: 30s
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - if: github.ref == 'refs/heads/master'
      name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - if: github.ref == 'refs/heads/master'
      name: If on master push image to GHCR
      run: docker push $GRPC_IMAGE_NAME:python_async_grpc_bench-complex_proto
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}


  python_grpc_bench:
    runs-on: ubuntu-latest
    needs:
    - set-image-name
    - changed
    if: fromJSON(needs.changed.outputs.base) || contains(needs.changed.outputs.files, 'python_grpc_bench/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build python_grpc_bench
      run: ./build.sh python_grpc_bench
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - name: Benchmark python_grpc_bench
      run: ./bench.sh python_grpc_bench
      env:
        GRPC_BENCHMARK_DURATION: 30s
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - if: github.ref == 'refs/heads/master'
      name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - if: github.ref == 'refs/heads/master'
      name: If on master push image to GHCR
      run: docker push $GRPC_IMAGE_NAME:python_grpc_bench-complex_proto
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}


  rust_grpcio_bench:
    runs-on: ubuntu-latest
    needs:
    - set-image-name
    - changed
    if: fromJSON(needs.changed.outputs.base) || contains(needs.changed.outputs.files, 'rust_grpcio_bench/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build rust_grpcio_bench
      run: ./build.sh rust_grpcio_bench
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - name: Benchmark rust_grpcio_bench
      run: ./bench.sh rust_grpcio_bench
      env:
        GRPC_BENCHMARK_DURATION: 30s
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - if: github.ref == 'refs/heads/master'
      name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - if: github.ref == 'refs/heads/master'
      name: If on master push image to GHCR
      run: docker push $GRPC_IMAGE_NAME:rust_grpcio_bench-complex_proto
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}


  rust_thruster_mt_bench:
    runs-on: ubuntu-latest
    needs:
    - set-image-name
    - changed
    if: fromJSON(needs.changed.outputs.base) || contains(needs.changed.outputs.files, 'rust_thruster_mt_bench/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build rust_thruster_mt_bench
      run: ./build.sh rust_thruster_mt_bench
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - name: Benchmark rust_thruster_mt_bench
      run: ./bench.sh rust_thruster_mt_bench
      env:
        GRPC_BENCHMARK_DURATION: 30s
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - if: github.ref == 'refs/heads/master'
      name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - if: github.ref == 'refs/heads/master'
      name: If on master push image to GHCR
      run: docker push $GRPC_IMAGE_NAME:rust_thruster_mt_bench-complex_proto
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}


  rust_thruster_st_bench:
    runs-on: ubuntu-latest
    needs:
    - set-image-name
    - changed
    if: fromJSON(needs.changed.outputs.base) || contains(needs.changed.outputs.files, 'rust_thruster_st_bench/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build rust_thruster_st_bench
      run: ./build.sh rust_thruster_st_bench
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - name: Benchmark rust_thruster_st_bench
      run: ./bench.sh rust_thruster_st_bench
      env:
        GRPC_BENCHMARK_DURATION: 30s
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - if: github.ref == 'refs/heads/master'
      name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - if: github.ref == 'refs/heads/master'
      name: If on master push image to GHCR
      run: docker push $GRPC_IMAGE_NAME:rust_thruster_st_bench-complex_proto
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}


  rust_tonic_mt_bench:
    runs-on: ubuntu-latest
    needs:
    - set-image-name
    - changed
    if: fromJSON(needs.changed.outputs.base) || contains(needs.changed.outputs.files, 'rust_tonic_mt_bench/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build rust_tonic_mt_bench
      run: ./build.sh rust_tonic_mt_bench
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - name: Benchmark rust_tonic_mt_bench
      run: ./bench.sh rust_tonic_mt_bench
      env:
        GRPC_BENCHMARK_DURATION: 30s
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - if: github.ref == 'refs/heads/master'
      name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - if: github.ref == 'refs/heads/master'
      name: If on master push image to GHCR
      run: docker push $GRPC_IMAGE_NAME:rust_tonic_mt_bench-complex_proto
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}


  rust_tonic_st_bench:
    runs-on: ubuntu-latest
    needs:
    - set-image-name
    - changed
    if: fromJSON(needs.changed.outputs.base) || contains(needs.changed.outputs.files, 'rust_tonic_st_bench/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build rust_tonic_st_bench
      run: ./build.sh rust_tonic_st_bench
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - name: Benchmark rust_tonic_st_bench
      run: ./bench.sh rust_tonic_st_bench
      env:
        GRPC_BENCHMARK_DURATION: 30s
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

    - if: github.ref == 'refs/heads/master'
      name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - if: github.ref == 'refs/heads/master'
      name: If on master push image to GHCR
      run: docker push $GRPC_IMAGE_NAME:rust_tonic_st_bench-complex_proto
      env:
        GRPC_IMAGE_NAME: ${{ needs.set-image-name.outputs.name }}

